# Generated by Django 3.0.7 on 2020-06-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_contents', models.TextField()),
                ('post_image', models.ImageField(upload_to='blogs_images')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
