# Generated by Django 3.0.7 on 2020-06-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.TextField(default=None, null=True)),
                ('rest_star', models.TextField(default=None, null=True)),
                ('rest_address', models.TextField(default=None, null=True)),
                ('rest_food', models.TextField(default=None, null=True)),
                ('rest_phone_number', models.TextField(default=None, null=True)),
                ('rest_sale', models.TextField(default=None, null=True)),
                ('rest_park', models.TextField(default=None, null=True)),
                ('rest_time', models.TextField(default=None, null=True)),
            ],
        ),
    ]
