# Generated by Django 3.0.7 on 2020-06-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200623_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='rest_address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_food',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_park',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_phone_number',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_sale',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_star',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_time',
            field=models.TextField(default=None, null=True),
        ),
    ]
