# Generated by Django 3.0.7 on 2020-06-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200623_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rest',
            old_name='rest_park',
            new_name='rest_break_time',
        ),
    ]
