# Generated by Django 3.0.7 on 2020-06-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_image', models.ImageField(upload_to='')),
                ('taste_value', models.CharField(choices=[('GOOD', 'Good'), ('SOSO', 'SoSo'), ('BAD', 'Bad')], default='SOSO', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owner_rest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='restaurant.Restaurant')),
            ],
        ),
    ]
